id: d3d1bcca20bc48208dc80d3ef04a1901
initial_creation_type: ocr
source_metadata:
  volumes:
    1b449d385ba14f1ab7470a6c4512c500:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
